version: 2

jobs:

  build:
    working_directory: ~
    docker:
      - image: zakred/circleci:node8-truffle
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: Installing NPM Modules
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Build contracts with truffle
          command: truffle compile

      - persist_to_workspace:
          root: ./
          paths:
            - ./

  test:
    docker:
      - image: zakred/circleci:node8-truffle
    working_directory: ~
    steps:
      - attach_workspace:
          at: ~/

      - run:
          name: Run test network and the tests
          command: |
            ganache-cli --mnemonic "candy maple cake sugar pudding cream honey rich smooth crumble sweet treat" --gasPrice 0 --port 9545 &
            sleep 8 &&
            truffle test --network local &&
            cd; sed -i '/.*reporter/ s/spec/mocha-junit-reporter/g' truffle.js; truffle test --network local

      - store_test_results:
          path: ~/

      - store_artifacts:
          path: ~/build/contracts

workflows:
  version: 2
  build_test:
    jobs:
      - build
      - test:
          requires:
            - build